import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { createTestRepository } from '../test/testRepository'
import { AppShell } from './AppShell'
describe('Winter Arc application', () => {
  it('reports missing connection settings', async () => {
    vi.resetModules()
    vi.doMock('../data/supabaseClient', () => ({ isSupabaseConfigured: false, supabase: null }))
    const { App } = await import('./App')
    render(<App />)
    expect(screen.getByText('This build is missing its Supabase connection settings.')).toBeInTheDocument()
    vi.doUnmock('../data/supabaseClient')
  })
  it('adds a catalog challenge through commitment confirmation', async () => {
    const repository = createTestRepository()
    render(<AppShell repository={repository} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Add challenge' }))
    fireEvent.click(screen.getByRole('button', { name: 'Select Deep work block' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm 1' }))
    fireEvent.click(screen.getByRole('button', { name: 'Commit' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(await screen.findByRole('button', { name: 'Complete Deep work block' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Ranks' }))
    expect(await screen.findByLabelText('Season rankings')).toBeInTheDocument()
  })
  it('keeps proof pending until review and allows another attempt after approval', async () => {
    const repository = createTestRepository()
    await repository.enrollChallenge('5k-run')
    render(<AppShell repository={repository} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Season' }))
    fireEvent.click(screen.getByRole('button', { name: 'Submit Compete in a 5K run for review' }))
    expect(await screen.findByText('Awaiting proof review')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Submit Compete in a 5K run for review' })).toBeDisabled()
    const [pending] = await repository.getPendingCompletions()
    await repository.reviewCompletion(pending.id,'confirmed')
    fireEvent.click(screen.getByRole('button', { name: 'Quests' }))
    await screen.findByText('Completed · add again for another attempt')
    fireEvent.click(screen.getByRole('button', { name: 'Add challenge' }))
    fireEvent.click(screen.getByRole('button', { name: 'Select Compete in a 5K run' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm 1' }))
    fireEvent.click(screen.getByRole('button', { name: 'Commit' }))
    await waitFor(() => expect(screen.getAllByRole('heading', { name: 'Compete in a 5K run' })).toHaveLength(2))
  })
  it('uses the generic baseline picker for weekly challenges', async () => {
    const repository = createTestRepository()
    const enroll = vi.spyOn(repository,'enrollChallenge')
    render(<AppShell repository={repository} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Add challenge' }))
    fireEvent.click(screen.getByRole('button', { name: 'Weekly' }))
    fireEvent.click(screen.getByRole('button', { name: 'Select Gym' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm 1' }))
    fireEvent.change(screen.getByRole('combobox', { name: 'Baseline for Gym' }), { target: { value: '5' } })
    fireEvent.click(screen.getByRole('button', { name: 'Commit' }))
    await waitFor(() => expect(enroll).toHaveBeenCalledWith('gym',5))
  })
  it('submits ideas without allowing players to assign rewards', async () => {
    const repository = createTestRepository()
    render(<AppShell repository={repository} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Suggest a challenge' }))
    expect(screen.queryByLabelText(/xp/i)).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Idea title'), { target: { value: 'Read before bed' } })
    fireEvent.change(screen.getByLabelText('Why should this be a challenge?'), { target: { value: 'Build a consistent reading habit.' } })
    fireEvent.click(screen.getByRole('button', { name: 'Submit idea' }))
    expect(await screen.findByText('Idea submitted for review.')).toBeInTheDocument()
    expect((await repository.getChallengeCatalog()).some((c) => c.title === 'Read before bed')).toBe(false)
  })
})
